
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: login_development

test:
  <<: *default
  database: login_test

production:
  <<: *default
  database: login_production
  username: ubuntu
  password:
